const npcCollection = {
  underwater: {
    mermaid: {
      x: 600,
      y: 450,
      isEdible: false,
      isAlive: true,
      isInvisible: false,
      script: ["Waiting for something to happen?"],
    },
    "fancy-shrimp": {
      x: 1600,
      y: 100,
      isEdible: true,
      isInvisible: false,
      isAlive: true,
      script: [
        "There's lots of tasty food in the sea!",
        "Try taking a bite with the F key!",
      ],
    },
    "shrimp-1": {
      x: 2500,
      y: 240,
      isEdible: true,
      isInvisible: false,
      isAlive: true,
      script: ["Please don't."],
    },
    "shrimp-2": {
      x: 3500,
      y: 500,
      isEdible: true,
      isInvisible: false,
      isAlive: true,
      script: [
        "All beautiful things must come to an end.",
        "Could you truly appreciate something that lasts forever?",
      ],
    },
    "fancy-octopus": {
      x: 4000,
      y: 420,
      isEdible: true,
      isInvisible: false,
      isAlive: true,
      script: [
        "Some of my less distinguished friends like to hide...",
        "Try using SPACE to find out where they are!",
      ],
    },
    "octopus-1": {
      x: 4380,
      y: 120,
      isEdible: true,
      isInvisible: true,
      isAlive: true,
      script: ["You found me!"],
    },
    "octopus-2": {
      x: 5240,
      y: 450,
      isEdible: true,
      isInvisible: true,
      isAlive: true,
      script: [
        "If you want the sun to shine through the clouds...",
        "The storm has to come sometime.",
      ],
    },
    "shrimp-3": {
      x: 5500,
      y: 440,
      isEdible: true,
      isInvisible: false,
      isAlive: true,
      script: [
        "The marvel of life is that there are no rules",
        "I guess some find that scary, but...",
        "That lets you create your own meaning.",
        "Isn't it wonderful?",
        "...",
        "....",
        "Say, shouldn't you be doing something?",
        {
          string: "w̴h̶̶̛ͩͬ̇̓͛̌̉̀̍̀ͬ͂͊͋́͏̶̶̡̨́͘͟͟͠͠a̴̵̷̴̶̴ͤ̉̔ͣͮͥ̿̔͊̆ͨ̈̔́̓͆̐͆͆̑͑̉ͦ͆̒ͪͪͩ͢͠҉̷̷̴̴̴̷̨̡̧̧́͢͟͞͝͏̵͞͡t̵̢́ͯ̉ͧ͒̿̽̋́ͣ̐ͩͮͣ̑̿̑̄̂ͣ́ͪ͐͊̌̏̆ͪ͑̐ͯ̾̂̍͒̈́͑̇̚̕҉͝͏̵̴̷̡͡͡͏҉͏̛̕͠҉̛҉̵̴̷̴̢̢̧́̀̀̀̕͜͝͡͝͝ ̶̵̵̵̷̧̧̨̛̛ͥͮͨ̐ͫ͊͌̈ͧ̃ͥ̈ͥ̇̌ͮͮ͒͐͌̆̈́̀̈ͤ̈́̉̽ͨ͆ͧ̂̅́͑̄̅͑ͬ̽̓ͤ̂͆̀̀́́̀̀́̀́̚̚͘̕͢͜͜͠͝͝͠͝҉̷̷̶̵̢̨̡͘͜͢͝͡͠͞͠a̶̡̨͐ͤ̔͐̑ͧ̈́͒ͨ̾͒ͩ͊̂͒̔͆̿̂̎̐́͋̓́̏͋̔͗̆ͬͦ̂̑ͨͥ͌̓̆̓ͤ̔̆̂͐̈́ͪͬ͗́̚̕̕͟͡͝͏̷̧̧̨̧́́̀̀͘͝҉̸̷̴̶̢̢̛̛͢͡͝͠͞͏̢̛̛͏̸̷̷̛̛͢͜͝͝r̶̶̵̨̊ͭ̐̈̃ͪ̾ͣͬ̎̽̂̀͐̇ͪ̓̈͌ͪͯͭ̐̐̍́̅̅̋̔̋̋ͨ̔̎ͥ̈͆͗̋̌̓ͦ̅ͣ̄́̐̐̀͘͜͜҉̶͜͟͠͏̛́͘҉̵̵̡̛̀̕͢͟͢҉̸̶̶̴̷̷̡̨̛̛͘͘͟͢͢͞͡͡͞͞e̵̵̷̴̸̴̷̶̢̧̢̨̨̡̢̢̛̛̛͒̉̂́̓̏̋̐ͨ̑͒͊̅̐̓̋͑ͥͦ͋̊ͤͭ̈ͬ̅͗̄ͬͦ̉͛ͮ͛̎̑̈́ͯͩ͑̐̐̀̀̀̀̚̕͘͘͘͘͜͜͢͜͡͠͞͠͡͠҉̴̛͞ ̃ͤ̆͆͐ͥ̓ͩͭͥͨͯ͂͗͒͌ͨ̑͂̾͑ͦ̑͊̇ͮͦ͐̍ͥ͆̆ͤͯ͏̶̶̡̨̛̀̀̀̕͡͞͞͠͞҉͏͝҉̵̴̢̡̛̛̀̕̕͢͡͡͠͠ŷ̶́ͫ̄̉ͧͤ̈ͫ̒͒ͫ̅̈̋̈́͂̄̈́̊ͦ͏́҉̷͘͢͏̸̶̴̸̵̶̡̛͢͢͠͝͡o̸̸͗̒̓̀ͣ̉̈́͢͏̶̷̕͢ù̷̶̶̶̧̧̞̖̱̙̯͎͇͝ ̵̸̧͡͡͏̷̧̨̡̛̀̀̕͘͟͢͜͠͞͏̲̰̭̱̳͕̳͓̹̝̘̘͈͖̭͉͙͉̫̰ͅa̸҉̷̵̷̡̨̛̕͜͡͡͏͏̴̢̢́͘͘͜͡͝͝͝͠͏͏̴̸̵͘҉̹̗̮̮̻̜̰̲͓͕̩͍̟̤̯̮͔̝͚͙͚̻̪̣͉̼̪̞̥̝ͅͅͅͅv̴̶̶̡̢̨̧̛͜͜͞҉̷̶̷̧̧̡̡̨́͟͟͞͝҉̸̶̧̡̧͢͏͠͠͏̸̴̸̵̡͖͚̱̦̰̞̠͙̤̖̤̗̜͚̟͉̤̞̳͙͔̗̟̭͖͍̖͙̫̳̟̙͔̳̫͕̩̩̬̼̘͜ͅͅǫ̢̨̀͘͢͜͜͟͡͞͠͡͏͏̸̵̸̨̢̀̀͘͢͢͠͠͏̵̷̷̧̧̨̛̕͟͜͞͞͡͠҉̴̴̷̭̺͔̣̩̳̩̱̥̺͍̙̩̯̼͇͈͖͚̦̪̯̗͎̼̱͙̲̱̱̙͍̳̭̫͚̺̥̺͔͚̫̥͙̝̟̞̙͘͟ͅì̵̶̴̵̶̶̵̵̧̡̡̧̨̢̛̀͘͘͢͢͟͝͡͠͝͡͡͡͠͏̶̨̛̀̕͞͝͏̶̡̧̀͘͜͢͜͠҉͚͉͕̣̞̖̪̜̝̪̣͓͈͕̲̟͈̘̩͇͓̺͉̭̪͉͍͖͍͔͔͙̟̭̮̘̼̹͚̹̫̺̤̫̤̺̰̹̪ͅd̴̴̸̡̨̛̀́̀́̕̕͘͟͜͢͢͜͡͝҉̷̴̸̵̸̵̴̢̡̨̢̨̛̛̻͚̬̲̩͇͍̞̞̣̙̠̯̰̩̟͍̟̫̝͓̘̠̯̦͍͓̫͇͓̞̬̣̖̭͎̜̰̘͚̹̹̱̲̜͎̕͡͠͞͝͡͝͡͝͞í̢͡҉̶̶̸̢̨̢̛̛́́͘̕͠͞͡͡͠͞͠͡͝͏͏̨̀͘̕͜͞҉̵̣̗̲̖͙̘͎̪̗̱͓̣̺̳̮̻͇̳̮̳̜͔͇̖̰̭͈̮̖͈̙̗͈̩̤͕͓̪͚̀̕͢ņ̸̷̴̵̷̢̀͜͡͏̡̨̀͘͜͢͞҉̷̡͡͏̛̕͞͠҉̳̘͉̹̤̬̦̫͚̤̘̘̼̭̳͈̜̳̯̣̩̫͓̦̺̫̥ͅg̸̴̷̸̵̷̨̡̧̧̛̜̤̭͉̣̬͇̘̭̟̙̖͇͙̀͘͘͢",
          alternateStyle: true,
        },
        { string: `ṣ̷̡̳̬̋͐̈́̂̋̕̕͝h̷̗̮̼̱̹̼̹̠̩͍̯̠̒́̄̓́͑̅͐̄̿̋̌̓́̀̀͑͐̑͛́̓͆̏̾̇̚͝ȩ̸̨̛͈͕̠͍̥̹̺̟̻̻̃̾̓̊̀̿͆̓̉̽̓̽̎͛̍͒̈͑̏͗̎͛͋̄̚̚͜͜͝ ̴̬̮͖̲͙͉͑̋̎͊ͅi̵̧̡̨̹͇̣͔̖͔̟̫̥̱̬̘̫͉͇̗̪͕̠̞̜͚͖̅̄̉̓͂́̿̾̒̉̊͒̒̌̿̇̔̉̐͐͐̃͌͛͋͆̆̏͐̎̚̕̚͜ͅs̴̡̡̢͉͓̯̮̻͖͚̗̺͚̜͖͈̩͇̬̒̒̅̇̀̀̔͂̄̐̃̒̈́͘͜͝ͅͅ ̶̨̧͙̗̲̳̘̹̯̣͇̤̠̠͓͍͕̼̺̜͙͕͍̗̦̲̖̯͎̜̖̼̬͎͓͍̄͋̓̿͌̊̿̅͆͗̔̃͒̐́͊̆͘͝ͅͅẅ̸̧̧̡̛̟̻̼͎̮̗͖̯̩̗̠̫͖̦̖̯̫̮̪̩̝̲̙̼̞͂̑͗̀̑̓̓͒̄̓͌̔̅̂̆̅̍͌̀͌͛̓͘̚͠͝ą̵̨̨̨̢͇̤͍̭͔̫͖̝̤̙̯̳̞̩̫̗̪͖̝̼̱̠͙̮͉̗̟͉͎̜͈̀̐̓̆̊̚i̶̧̧̡̨̛̜̤̝̖̟̯̘͙̼͚̩̘̥̖̫̲̝͇̤̘͈̭̪͔̘̟͍̗̝͙̤̭͌̏͋̔̕ṱ̶̡̧̧̧̧̨̨̛͚͕͙̝͓̦͍̮͍͍̝̜̙͕̺͚̺̩̩̘͙̻̟͚͙̘̟̦̮̼̪̿̊͆͗͂͜͝͠ͅi̵̡̛̥͙̜̖̬͔̥̬̺̳̰͕̰͉̋͌̾̋̈̑́́̽̽́̄̓͆̂̈̊̋̊̾̈́̌́͒͑̃̍̎͋̈̍̓͋͗̚̚͘͜͝n̷̫̝̺̗͇͔̠̕̕͠ǵ̶̹̘̃̾̄͆̆̓͗`, alternateStyle: true },
      ],
    },
    "octopus-3": {
      x: 6000,
      y: 180,
      isEdible: true,
      isInvisible: true,
      isAlive: true,
      script: [
        "Have you seen my family?",
        "They were just here, they look just like me...",
      ],
    },
    submarine: {
      x: 8000,
      y: 300,
      isEdible: true,
      isInvisible: false,
      isAlive: true,
      script: ["I don't think you can talk to a submarine"],
    },
  },
  void: {
    "flaming-bus": {
      x: 2660,
      y: 550,
      isEdible: false,
      isInvisible: false,
      isAlive: true,
      script: ["A bus on fire?", "...", "Why is it familiar?"],
    },
    "corrupted-whale": {
      x: 5860,
      y: 550,
      isEdible: false,
      isInvisible: false,
      isAlive: true,
      script: [".", "..", "...", "She needed you...", "WHERE WERE YOU?"],
    },
    "void-mermaid-standing": {
      x: 9040,
      y: 550,
      isEdible: false,
      isInvisible: false,
      isAlive: true,
      checkForCompleteDialog: true,
      script: [
        "Don't you have something you need to be doing?",
        "...",
        "Always...",
        "You said always...",
      ],
    },
    "void-mermaid-screaming": {
      x: 9015,
      y: 550,
      isEdible: false,
      isInvisible: false,
      isAlive: true,
      notInteractive: true,
    },
  },
  graveyard: {},
};

export default npcCollection;
